version: '3.8'

services:
  website-monitor:
    build: .
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - STRIPE_SECRET_KEY
    ports:
      - "5002:5002"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped