"""add notification email to user

Revision ID: 8c38ae6f06d5
Revises: 2203a0f673c4
Create Date: 2025-01-29 13:41:03.545611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c38ae6f06d5'
down_revision = '2203a0f673c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notification_email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('notifications_enabled', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notifications_enabled')
    op.drop_column('user', 'notification_email')
    # ### end Alembic commands ###
